pipeline {  
        
    agent { label 'worker_agent' }
    
    environment {
        MONGODB_TEST_URL = credentials('MONGODB_TEST_URL')
        REDIS_HOST = credentials('REDIS_HOST')
        REDIS_PORT = credentials('REDIS_PORT')
        REDIS_PASSWORD = credentials('REDIS_PASSWORD')
        REDIS_USERNAME = credentials('REDIS_USERNAME')
        DOCKER_USERNAME = credentials('DOCKER_USERNAME')
        IMAGE_NAME = "${DOCKER_USERNAME}/cloudvault-backend:${BUILD_NUMBER}"
        USER_EMAIL = credentials('ALERT_EMAIL')
    }
    
    stages {

        stage('Install dependency') {
            steps {
                dir('backend') {
                    sh '''
                        if [ ! -d node_modules ]; then
                            echo "node_modules not found. Running npm install."
                            npm install

                        elif [ package.json -nt node_modules ]; then
                            echo "package.json changed. Running npm install."
                            npm install

                        else
                            echo "Using cached dependency"
                        fi
                    '''
                }
            }
        }
        
        stage('Run test') {
            steps {
                dir('backend') {
                    sh '''
                    export NODE_ENV=test
                    export JWT_SECRET=tempJwtSecret@
                    npm test
                    '''
                    echo 'Test successful'
                }
            }
        }
        
        stage('Build image') {
            steps {
                dir('backend') {
                    echo 'Starting image build...'
                    sh 'docker build -t $IMAGE_NAME .'
                    echo 'Build successful'
                }
            }
        }
        /*
        stage('Scan image') {
            steps {
                echo 'Starting image scanning...'
                sh 'trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME'
                echo 'Scan completed'
            }
        }
        */
        stage('Push to registry') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'DOCKERHUB_CREDS',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    echo 'Pushing image to registry...'
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push $IMAGE_NAME'
                    echo 'Image pushed to registry'
                    sh 'docker logout'
                }
            }
        }
        
        
        stage('Update EKS deployment') {
            steps {
                sh '''
                   kubectl set image deployment/cloudvault-backend cloudvault=$IMAGE_NAME
                   kubectl rollout status deployment/cloudvault-backend --timeout=180s
                 '''
            }
        }
        
    }

    post {
        success {
            mail to: env.USER_EMAIL,
            subject: "SUCCESS ! Pipeline #${BUILD_NUMBER} executed",
            body: """
                Cloudvault backend pipeline executed successfully.

                Build Number : ${BUILD_NUMBER}
                View full logs here:
                ${BUILD_URL}
                """
        }
        
        failure {

            script {
            def reason = "Failure reason unavailable. Please check logs."

            try {
                reason = currentBuild.rawBuild.getLog(10).join('\n')
            } catch (e) {
                
            }
            
            mail to: env.USER_EMAIL,
            subject: "ERROR ! Pipeline #${BUILD_NUMBER} stopped",
            body: """
                   Cloudvault backend pipeline stopped due to error.
                   Build Number : ${BUILD_NUMBER}
                   Failed Stage : ${STAGE_NAME}

                   Failure Reason (last log lines):
                   ${reason}

                   View full logs here:
                   ${BUILD_URL}
                 """
            }
        }

        always {
            echo 'Pipeline execution completed'
        }
    }
}



